version: '3.8'
services:
  # 1. HR Database (PostgreSQL) - The Source of Truth
  hr-db:
    image: postgres:15-alpine
    container_name: hr-db
    environment:
      POSTGRES_USER: hr_admin
      POSTGRES_PASSWORD: HR_Secure_Password_2026
      POSTGRES_DB: hr_database
    ports:
      - "5432:5432"
    volumes:
      - hr_db_data:/var/lib/postgresql/data
      - ./init-hr-db.sql:/docker-entrypoint-initdb.d/init-hr-db.sql
    networks:
      - iam-network

  # 2. LDAP Directory (OpenLDAP) - Corporate Directory
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    command: --copy-service --loglevel debug
    environment:
      LDAP_ORGANISATION: Enterprise IT
      LDAP_DOMAIN: corporate.local
      LDAP_ADMIN_PASSWORD: LDAP_Admin_Password_2026
      LDAP_CONFIG_PASSWORD: LDAP_Config_Password_2026
      LDAP_TLS: "True"
      LDAP_TLS_CRT_FILENAME: ldap.crt
      LDAP_TLS_KEY_FILENAME: ldap.key
      LDAP_TLS_CA_CRT_FILENAME: ca.crt
      LDAP_TLS_VERIFY_CLIENT: never
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ./ldap.crt:/container/service/slapd/assets/certs/ldap.crt
      - ./ldap.key:/container/service/slapd/assets/certs/ldap.key
      - ./ca.crt:/container/service/slapd/assets/certs/ca.crt
    networks:
      - iam-network


  # keycloak:
   # image: quay.io/keycloak/keycloak:24.0
    #command: start-dev --hostname-strict=false
    #environment:
     # - KEYCLOAK_ADMIN=admin
      #- KEYCLOAK_ADMIN_PASSWORD=admin
      #- KC_PROXY=edge
    #ports:
     # - "8080:8080"
    #depends_on:
     # - openldap */

  # 3. Keycloak - Identity Provider (IdP)
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    #command: ["start-dev","--http-port=8080"]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
      KC_PROXY: "edge"
      KC_FEATURES: token-exchange
      #Clean mapping format with colon and hyphen
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    depends_on:
      - openldap
    networks:
      - iam-network  
    volumes:
      - ./keycloak-import:/opt/keycloak/data/import
    command: start-dev --import-realm

  # grafana:
   # image: grafana/grafana:latest
    #ports:
     # - "3000:3000"
    #environment:
     # - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      #- GF_AUTH_GENERIC_OAUTH_NAME=Keycloak-Corporate
      #- GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP=true
      #- GF_AUTH_GENERIC_OAUTH_CLIENT_ID=grafana-enterprise
      #- GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=GitWkCuJO1hnKgWq51ZtlgTZzbOi6Rh2
      #- GF_AUTH_GENERIC_OAUTH_SCOPES=openid profile email
      #- GF_SERVER_ROOT_URL=https://upgraded-memory-g4rvw9gxgq7qfw77v-3000.app.github.dev/
      #- GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://upgraded-memory-g4rvw9gxgq7qfw77v-8080.app.github.dev/realms/Corporate-Employees/protocol/openid-connect/auth
      #- GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://upgraded-memory-g4rvw9gxgq7qfw77v-8080.app.github.dev/realms/Corporate-Employees/protocol/openid-connect/token
      #- GF_AUTH_GENERIC_OAUTH_API_URL=https://upgraded-memory-g4rvw9gxgq7qfw77v-8080.app.github.dev/realms/Corporate-Employees/protocol/openid-connect/userinfo */

    # 4. Grafana - The Target Application
  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_NAME=Keycloak
      - GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP=true
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=grafana
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=EF3puQPcHgfxlg9pWLe7BXlwPVLG6nwc
      - GF_AUTH_GENERIC_OAUTH_SCOPES=openid profile email
      - GF_SERVER_ROOT_URL=https://upgraded-memory-g4rvw9gxgq7qfw77v-3000.app.github.dev/
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://upgraded-memory-g4rvw9gxgq7qfw77v-8080.app.github.dev/realms/corporate/protocol/openid-connect/auth
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://upgraded-memory-g4rvw9gxgq7qfw77v-8080.app.github.dev/realms/corporate/protocol/openid-connect/token
      - GF_AUTH_GENERIC_OAUTH_API_URL=https://upgraded-memory-g4rvw9gxgq7qfw77v-8080.app.github.dev/realms/corporate/protocol/openid-connect/userinfo
      - GF_SECURITY_COOKIE_SECURE=true
      - GF_SECURITY_COOKIE_SAMESITE=none
    depends_on:
      - keycloak
    networks:
      - iam-network
  iam-sync-worker:
    build: .
    container_name: iam_sync_worker
    environment:
      - DB_HOST=hr-db
      - DB_NAME=hr_database
      - DB_USER=hr_admin
      - DB_PASSWORD=HR_Secure_Password_2026
      - LDAP_SERVER=openldap
      - LDAP_BIND_DN=cn=admin,dc=corporate,dc=local 
      - LDAP_BIND_PASSWORD=LDAP_Admin_Password_2026
    depends_on: 
      - hr-db
      - openldap  
    networks:
      - iam-network  
    restart: always

  hr-ui:
    build:
      context: ./hr-ui
      dockerfile: dockerfile.ui
    container_name: hr_web_ui
    environment:
      - DB_HOST=hr-db
      - DB_NAME=hr_database
      - DB_USER=hr_admin
      - DB_PASSWORD=HR_Secure_Password_2026
    ports:
      - "5000:5000"
    depends_on:
      - hr-db
    networks:
      - iam-network 

volumes:
  keycloak_data:
  hr_db_data:
  ldap_data:
  ldap_config:

networks:
  iam-network:
    driver: bridge